syntax = "proto3";

package arcabank.grpc;

option java_multiple_files = true;
option java_package = "com.arcabank.grpc";
option java_outer_classname = "ArcaBankIntercomProto";

service AccountProvisioningService {
  rpc CreateInitialAccount (CreateAccountRequest) returns (CreateAccountResponse);
}

message CreateAccountRequest {
  string user_id = 1;
  ProtoCurrency currency = 2; // like UAH USD EUR etc
  string first_name = 3;
  string last_name = 4;
  string pin = 5;
}

message CreateAccountResponse {
  string account_id = 1;
  bool success = 3;
}

enum ProtoCurrency {
  CURRENCY_UNSPECIFIED = 0;
  CURRENCY_UAH = 1;
  CURRENCY_USD = 2;
  CURRENCY_EUR = 3;
}
