server:
  port: 8081

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/arcabank

grpc:
  server:
    port: 9091

keycloak:
  server-url: http://localhost:8180
  realm: arcabank
  client-id: arcabank-admin-client
  client-secret: arcabank-super-secret-key-123
